# Generated by Django 3.0.8 on 2020-10-07 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='list_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller', models.CharField(max_length=64)),
                ('tittle', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('starting_bid', models.IntegerField()),
                ('catagory', models.CharField(max_length=64)),
                ('image', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
