# Generated by Django 3.0.8 on 2020-10-07 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_list_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list_item',
            old_name='tittle',
            new_name='title',
        ),
    ]
