# Generated by Django 3.0.8 on 2020-10-18 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_bid_watchlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=64)),
                ('item_id', models.IntegerField()),
                ('content', models.TextField()),
                ('createdon', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
