# Generated by Django 3.0.8 on 2020-10-21 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_winner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='winner',
            name='item_id',
        ),
        migrations.AddField(
            model_name='winner',
            name='title',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
